### ISSUE TITLE
ImportError: cannot import name QtWidgets 

### ISSUE THREAD

**Issue by llobetv** [neoanalysis/NeoAnalysis#1]
Hi,

I'm trying to install you're library to test it on my data but i got this error : 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/nsr/llobet/miniconda2/envs/neoAnalysis/lib/python2.7/site-packages/NeoAnalysis/__init__.py", line 2, in <module>
    from NeoAnalysis.spikedetection import SpikeDetection
  File "/users/nsr/llobet/miniconda2/envs/neoAnalysis/lib/python2.7/site-packages/NeoAnalysis/spikedetection.py", line 6, in <module>
    from .pyqtgraph.Qt import QtCore, QtGui, QtWidgets
ImportError: cannot import name QtWidgets

I've got PyQt4 and it's probably come from import QtWidgets that doesn't exist in PyQt4 (function seems to be in QtGui). In Qt.py You begin to transfer function of QtWidget to QtGui to allow compatibility with Qt4 and Qt5 but you didn't do it for QtWidget.QInputDialog and QtWidget.QMessageBox that you use in analogfilter.py, spikedetection.py and spikesorting.py where you try to import QtWidget.

I change QtWidget to QtGui and i'll see if it's working when i'll manage to convert my data in you're format.

Best,

Victor Llobet,
PhD Student

**Comment by neoanalysis** [comment]
Sorry to reply so late to you. Does the problem still exist? 
I suggest you install Anaconda instead of minicoda. For the reason that lots dependent pkgs which NeoAnalysis needs, are already included in the Anaconda. And you only need to install a few pkgs according to the manual. 
If the problem still exists, please let me know.
Best Wishes.
